export const generateAAReportQuery = (startDate: string, endDate: string) => {
  return `
    DECLARE @yesterday DATETIME = '${startDate}';
    DECLARE @today DATETIME = '${endDate}';
    DECLARE @date1 DATETIME = DATEADD(DAY, -365, @today);
    DECLARE @date2 DATETIME = @today;

    /* ==============================
       Buat CTE untuk setiap FOCUS_ANALYTICS
    ============================== */
    WITH F1 AS (
      SELECT
        LOG_ID,
        PRODUCT_NO,
        EMP_NO,
        CASE
          WHEN LEN(LOG_FILENAME) = 16 THEN SUBSTRING(LOG_FILENAME, CHARINDEX('.', LOG_FILENAME) - 12, 11)
          WHEN LEN(LOG_FILENAME) = 17 THEN SUBSTRING(LOG_FILENAME, CHARINDEX('.', LOG_FILENAME) - 13, 11)
        END AS SN,
        CASE
          WHEN LEN(LOG_FILENAME) = 16 THEN SUBSTRING(LOG_FILENAME, CHARINDEX('.', LOG_FILENAME) - 1, 1)
          WHEN LEN(LOG_FILENAME) = 17 THEN SUBSTRING(LOG_FILENAME, CHARINDEX('.', LOG_FILENAME) - 2, 2)
        END AS MACHINE_ID,
        TEST_RESULT,
        CREATE_DATETIME,
        TEST_DATETIME
      FROM [dbo].[RG_AA_IOT]
      WHERE TEST_ITEM = 'FOCUS_ANALYTICS_1'
        AND TEST_DATETIME BETWEEN @date1 AND @date2
    ),
    F2 AS (
      SELECT
        LOG_ID,
        PRODUCT_NO,
        EMP_NO,
        CASE
          WHEN LEN(LOG_FILENAME) = 16 THEN SUBSTRING(LOG_FILENAME, CHARINDEX('.', LOG_FILENAME) - 12, 11)
          WHEN LEN(LOG_FILENAME) = 17 THEN SUBSTRING(LOG_FILENAME, CHARINDEX('.', LOG_FILENAME) - 13, 11)
        END AS SN,
        CASE
          WHEN LEN(LOG_FILENAME) = 16 THEN SUBSTRING(LOG_FILENAME, CHARINDEX('.', LOG_FILENAME) - 1, 1)
          WHEN LEN(LOG_FILENAME) = 17 THEN SUBSTRING(LOG_FILENAME, CHARINDEX('.', LOG_FILENAME) - 2, 2)
        END AS MACHINE_ID,
        TEST_RESULT,
        CREATE_DATETIME,
        TEST_DATETIME
      FROM [dbo].[RG_AA_IOT]
      WHERE TEST_ITEM = 'FOCUS_ANALYTICS_2'
        AND TEST_DATETIME BETWEEN @date1 AND @date2
    ),
    F3 AS (
      SELECT
        LOG_ID,
        PRODUCT_NO,
        EMP_NO,
        CASE
          WHEN LEN(LOG_FILENAME) = 16 THEN SUBSTRING(LOG_FILENAME, CHARINDEX('.', LOG_FILENAME) - 12, 11)
          WHEN LEN(LOG_FILENAME) = 17 THEN SUBSTRING(LOG_FILENAME, CHARINDEX('.', LOG_FILENAME) - 13, 11)
        END AS SN,
        CASE
          WHEN LEN(LOG_FILENAME) = 16 THEN SUBSTRING(LOG_FILENAME, CHARINDEX('.', LOG_FILENAME) - 1, 1)
          WHEN LEN(LOG_FILENAME) = 17 THEN SUBSTRING(LOG_FILENAME, CHARINDEX('.', LOG_FILENAME) - 2, 2)
        END AS MACHINE_ID,
        TEST_RESULT,
        CREATE_DATETIME,
        TEST_DATETIME
      FROM [dbo].[RG_AA_IOT]
      WHERE TEST_ITEM = 'FOCUS_ANALYTICS_3'
        AND TEST_DATETIME BETWEEN @date1 AND @date2
    ),
    F4 AS (
      SELECT
        LOG_ID,
        PRODUCT_NO,
        EMP_NO,
        CASE
          WHEN LEN(LOG_FILENAME) = 16 THEN SUBSTRING(LOG_FILENAME, CHARINDEX('.', LOG_FILENAME) - 12, 11)
          WHEN LEN(LOG_FILENAME) = 17 THEN SUBSTRING(LOG_FILENAME, CHARINDEX('.', LOG_FILENAME) - 13, 11)
        END AS SN,
        CASE
          WHEN LEN(LOG_FILENAME) = 16 THEN SUBSTRING(LOG_FILENAME, CHARINDEX('.', LOG_FILENAME) - 1, 1)
          WHEN LEN(LOG_FILENAME) = 17 THEN SUBSTRING(LOG_FILENAME, CHARINDEX('.', LOG_FILENAME) - 2, 2)
        END AS MACHINE_ID,
        TEST_RESULT,
        CREATE_DATETIME,
        TEST_DATETIME
      FROM [dbo].[RG_AA_IOT]
      WHERE TEST_ITEM = 'FOCUS_ANALYTICS_4'
        AND TEST_DATETIME BETWEEN @date1 AND @date2
    ),
    JOIN_TABLE AS (
      SELECT
        F1.LOG_ID AS LOG_ID_1,
        F2.LOG_ID AS LOG_ID_2,
        F3.LOG_ID AS LOG_ID_3,
        F4.LOG_ID AS LOG_ID_4,
        F1.EMP_NO,
        F1.PRODUCT_NO,
        F1.SN,
        F1.MACHINE_ID,
        F1.TEST_RESULT AS F1_RESULT,
        F2.TEST_RESULT AS F2_RESULT,
        F3.TEST_RESULT AS F3_RESULT,
        F4.TEST_RESULT AS F4_RESULT,
        F1.CREATE_DATETIME,
        F1.TEST_DATETIME
      FROM F1
      LEFT JOIN F2 ON F1.SN = F2.SN AND F1.MACHINE_ID = F2.MACHINE_ID AND F1.TEST_DATETIME = F2.TEST_DATETIME
      LEFT JOIN F3 ON F1.SN = F3.SN AND F1.MACHINE_ID = F3.MACHINE_ID AND F1.TEST_DATETIME = F3.TEST_DATETIME
      LEFT JOIN F4 ON F1.SN = F4.SN AND F1.MACHINE_ID = F4.MACHINE_ID AND F1.TEST_DATETIME = F4.TEST_DATETIME
    ),
    OK_TABLE AS (
      SELECT *,
        ROW_NUMBER() OVER (PARTITION BY SN ORDER BY LOG_ID_1 DESC) AS RowNum
      FROM JOIN_TABLE
      WHERE (F1_RESULT LIKE '%OK%' AND F2_RESULT LIKE '%OK%' AND F3_RESULT LIKE '%OK%' AND F4_RESULT LIKE '%OK%')
         OR (F1_RESULT LIKE '%OK%' AND F2_RESULT LIKE '%OK%' AND F3_RESULT LIKE '%OK%' AND (MACHINE_ID = '5' OR MACHINE_ID = '7'))
    ),
    NG_TABLE AS (
      SELECT *,
        ROW_NUMBER() OVER (PARTITION BY SN ORDER BY LOG_ID_1 DESC) AS RowNum
      FROM JOIN_TABLE
      WHERE F1_RESULT LIKE '%NG%' OR F2_RESULT LIKE '%NG%' OR F3_RESULT LIKE '%NG%' OR F4_RESULT LIKE '%NG%'
    ),
    ALL_TABLE AS (
      SELECT *,
        ROW_NUMBER() OVER (PARTITION BY SN ORDER BY LOG_ID_1 DESC) AS RowNum
      FROM JOIN_TABLE
    ),
    OK_PRODUCT_LIST AS (
      SELECT SN, MACHINE_ID FROM OK_TABLE WHERE RowNum = 1
    ),
    OK_PRODUCT_LIST_DAILY AS (
      SELECT SN, MACHINE_ID FROM OK_TABLE WHERE RowNum = 1 AND TEST_DATETIME BETWEEN @yesterday AND @today
    ),
    NG_PRODUCT_LIST AS (
      SELECT NG.SN, NG.MACHINE_ID
      FROM NG_TABLE NG
      LEFT JOIN OK_PRODUCT_LIST OK ON NG.SN = OK.SN
      WHERE NG.RowNum = 1 AND OK.SN IS NULL
    ),
    NG_PRODUCT_LIST_DAILY AS (
      SELECT NG.SN, NG.MACHINE_ID
      FROM NG_TABLE NG
      LEFT JOIN OK_PRODUCT_LIST OK ON NG.SN = OK.SN
      WHERE NG.RowNum = 1 AND OK.SN IS NULL AND TEST_DATETIME BETWEEN @yesterday AND @today
    ),
    OK_COUNT AS (
      SELECT MACHINE_ID, COUNT(*) AS COUNTS FROM OK_PRODUCT_LIST GROUP BY MACHINE_ID
    ),
    NG_COUNT AS (
      SELECT MACHINE_ID, COUNT(*) AS COUNTS FROM NG_PRODUCT_LIST GROUP BY MACHINE_ID
    ),
    RETRY_COUNT AS (
      SELECT MACHINE_ID, SUM(RowNum - 1) AS COUNTS
      FROM (
        SELECT *, ROW_NUMBER() OVER (PARTITION BY SN ORDER BY RowNum DESC) AS rn
        FROM ALL_TABLE
      ) AS sub
      WHERE rn = 1
      GROUP BY MACHINE_ID
    ),
    OK_COUNT_DAILY AS (
      SELECT MACHINE_ID, COUNT(*) AS COUNTS FROM OK_PRODUCT_LIST_DAILY GROUP BY MACHINE_ID
    ),
    NG_COUNT_DAILY AS (
      SELECT MACHINE_ID, COUNT(*) AS COUNTS FROM NG_PRODUCT_LIST_DAILY GROUP BY MACHINE_ID
    ),
    RETRY_COUNT_DAILY AS (
      SELECT MACHINE_ID, SUM(RowNum - 1) AS COUNTS
      FROM (
        SELECT *, ROW_NUMBER() OVER (PARTITION BY SN ORDER BY RowNum DESC) AS rn
        FROM ALL_TABLE
      ) AS sub
      WHERE rn = 1 AND TEST_DATETIME BETWEEN @yesterday AND @today
      GROUP BY MACHINE_ID
    )

    SELECT 
      OK_COUNT.MACHINE_ID,
      ISNULL(OK_COUNT_DAILY.COUNTS, 0) AS OK,
      ISNULL(NG_COUNT_DAILY.COUNTS, 0) AS NG,
      ISNULL(RETRY_COUNT_DAILY.COUNTS, 0) AS RETRY,
      ISNULL(OK_COUNT.COUNTS, 0) AS OK_YEAR,
      ISNULL(NG_COUNT.COUNTS, 0) AS NG_YEAR,
      ISNULL(RETRY_COUNT.COUNTS, 0) AS RETRY_YEAR,
      CASE 
        WHEN (ISNULL(OK_COUNT_DAILY.COUNTS,0) + ISNULL(NG_COUNT_DAILY.COUNTS,0) + ISNULL(RETRY_COUNT_DAILY.COUNTS,0)) = 0 THEN 0
        ELSE CAST(ISNULL(RETRY_COUNT_DAILY.COUNTS,0) AS FLOAT) / 
             (ISNULL(OK_COUNT_DAILY.COUNTS,0) + ISNULL(NG_COUNT_DAILY.COUNTS,0) + ISNULL(RETRY_COUNT_DAILY.COUNTS,0)) * 100
      END AS RetestRate_Daily,
      CASE 
        WHEN (ISNULL(OK_COUNT.COUNTS,0) + ISNULL(NG_COUNT.COUNTS,0) + ISNULL(RETRY_COUNT.COUNTS,0)) = 0 THEN 0
        ELSE CAST(ISNULL(RETRY_COUNT.COUNTS,0) AS FLOAT) / 
             (ISNULL(OK_COUNT.COUNTS,0) + ISNULL(NG_COUNT.COUNTS,0) + ISNULL(RETRY_COUNT.COUNTS,0)) * 100
      END AS RetestRate_Yearly
    FROM OK_COUNT
    LEFT JOIN NG_COUNT ON OK_COUNT.MACHINE_ID = NG_COUNT.MACHINE_ID
    LEFT JOIN RETRY_COUNT ON OK_COUNT.MACHINE_ID = RETRY_COUNT.MACHINE_ID
    LEFT JOIN OK_COUNT_DAILY ON OK_COUNT.MACHINE_ID = OK_COUNT_DAILY.MACHINE_ID
    LEFT JOIN NG_COUNT_DAILY ON OK_COUNT.MACHINE_ID = NG_COUNT_DAILY.MACHINE_ID
    LEFT JOIN RETRY_COUNT_DAILY ON OK_COUNT.MACHINE_ID = RETRY_COUNT_DAILY.MACHINE_ID
    WHERE OK_COUNT.MACHINE_ID != 0
    ORDER BY CAST(OK_COUNT.MACHINE_ID AS INT);
  `;
};